name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HACK_KANSAI_2024_WEB_TUTORIAL }}
          projectId: hack-kansai-2024-web-tutorial
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
